adapter_name_or_path: saves/Qwen1.5-14B-Chat/lora/qwen1.5-14b-iepile-lora
bf16: true
cutoff_len: 3500
dataset: new1468
dataset_dir: data
ddp_timeout: 180000000
do_train: true
eval_steps: 300
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 4
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 64
lora_dropout: 0.1
lora_rank: 32
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 0.5
max_samples: 100000
model_name_or_path: /root/autodl-tmp/qwen/Qwen1.5-14B-Chat
num_train_epochs: 10.0
optim: adamw_torch
output_dir: saves/Qwen1.5-14B-Chat/lora/train_2024-07-17-16-50-02
packing: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 300
stage: sft
template: qwen
use_dora: true
val_size: 0.1
warmup_steps: 100
